### ISSUE TITLE
Custome database search error

### ISSUE THREAD

**Issue by javanOkendo** [Nesvilab/philosopher#143]
I am trying to do the sequence database search and I get the below error using the custome database which I created. I added the added the contaminants and the decot but the program still fails. Can you help?
time="21:12:57" level=info msg="Executing Workspace  v3.2.3"
time="21:12:58" level=info msg="Creating workspace"
time="21:12:58" level=warning msg="A meta data folder was found and will not be overwritten. "
time="21:12:58" level=info msg=Done
time="21:12:59" level=info msg="Executing Pipeline  v3.2.3"
time="21:12:59" level=info msg="Initiating the workspace on bal_mzML_raw_files"
time="21:13:00" level=info msg="Creating workspace"
time="21:13:00" level=warning msg="A meta data folder was found and will not be overwritten. "
time="21:13:00" level=info msg="Processing database"
time="21:13:06" level=info msg="Running the Database Search on all data"
MSFragger version MSFragger-2.3
Batmass-IO version 1.17.2
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 1.8.0_242, OpenJDK 64-Bit Server VM, Oracle Corporation
JVM started with 28 GB memory

Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T006_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T007_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T009_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T010_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T011_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T013_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T014_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T015_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T025_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T026_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T027_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T037_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T042_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T049_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T051_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T052_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T053_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T054_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T061_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T062_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T064_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T069_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T073_FT_R2.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T075_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T077_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T080_FT.mzML...
Checking /scratch/oknjav001/bal_mzML_raw_files/mzmltraining27files/170909_CH_C1_T084_FT_R2.mzML...

************************************MAIN SEARCH************************************
variable_mod_04 has an empty value.
Parameters:
num_threads = 40
database_name = /scratch/oknjav001/bal_mzML_raw_files/humanDatabase/metanovo.fasta
decoy_prefix = rev_
precursor_mass_lower = -150.0
precursor_mass_upper = 500.0
precursor_mass_units = 1
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 0
write_calibrated_mgf = false
isotope_error = 0/1/2
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5, 3.5)
fragment_ion_series = b,y
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 1
allowed_missed_cleavage = 2
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_peptide = 5
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 35
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
deisotope = 1
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
remove_precursor_peak = 0
remove_precursor_range = -1.5,1.5
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
mass_diff_to_variable_mod = false
variable_mod_01 = 15.99490 M 3
variable_mod_02 = 42.01060 [^ 1
variable_mod_03 = 79.96633 STY 3
add_A_alanine = 0.000000
add_C_cysteine = 57.021464
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.000000
add_E_glutamic_acid = 0.000000
add_F_phenylalanine = 0.000000
add_G_glycine = 0.000000
add_H_histidine = 0.000000
add_I_isoleucine = 0.000000
add_K_lysine = 0.000000
add_L_leucine = 0.000000
add_M_methionine = 0.000000
add_N_asparagine = 0.000000
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_P_proline = 0.000000
add_Q_glutamine = 0.000000
add_R_arginine = 0.000000
add_S_serine = 0.000000
add_T_threonine = 0.000000
add_V_valine = 0.000000
add_W_tryptophan = 0.000000
add_Y_tyrosine = 0.000000
Number of unique peptides
	of length 7: 6432146
	of length 8: 6569718
	of length 9: 6488623
	of length 10: 6357368
	of length 11: 6197828
	of length 12: 6028507
	of length 13: 5846009
	of length 14: 5647251
	of length 15: 5444344
	of length 16: 5235336
	of length 17: 5022782
	of length 18: 4808913
	of length 19: 4594871
	of length 20: 4381725
	of length 21: 4169653
	of length 22: 3962473
	of length 23: 3763597
	of length 24: 3566065
	of length 25: 3375272
	of length 26: 3191389
	of length 27: 3013796
	of length 28: 2842403
	of length 29: 2679528
	of length 30: 2522922
	of length 31: 2373583
	of length 32: 2232546
of length 33: 2099181
	of length 34: 1972615
	of length 35: 1852299
In total 122672743 peptides.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at edu.umich.andykong.msfragger.H.a(Unknown Source)
	at edu.umich.andykong.msfragger.F.a(Unknown Source)
	at edu.umich.andykong.msfragger.j.a(Unknown Source)
	at edu.umich.andykong.msfragger.x.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
time="21:17:42" level=info msg="Running the validation and inference on bal_mzML_raw_files"
time="21:17:42" level=info msg="Executing PeptideProphet on bal_mzML_raw_files"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
philosopher/lib/ext/peptideprophet.interactParser(0xc0030b8240, 0x38, 0xc0030b8280, 0x37, 0xc0030b82c0, 0x3e, 0xc0030b8300, 0x3c, 0xc0030b8340, 0x3b, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:218 +0x224d
philosopher/lib/ext/peptideprophet.PeptideProphet.Execute(0xc0030b8240, 0x38, 0xc0030b8280, 0x37, 0xc0030b82c0, 0x3e, 0xc0030b8300, 0x3c, 0xc0030b8340, 0x3b, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:125 +0x1bd
philosopher/lib/ext/peptideprophet.Run(0xc003a58060, 0x24, 0xc0030b81c0, 0x39, 0xc003a580c0, 0x29, 0xc00042e0a0, 0x48, 0xc0030b8200, 0x3f, ...)
	/workspace/philosopher/lib/ext/peptideprophet/peptideprophet.go:70 +0x4d0
philosopher/lib/pip.Prophets(0xc003a58090, 0x24, 0xc0030b8100, 0x39, 0xc003a58120, 0x29, 0xc00383c280, 0x48, 0xc0030b8140, 0x3f, ...)
	/workspace/philosopher/lib/pip/pip.go:255 +0xa6c
philosopher/cmd.glob..func13(0x86cd460, 0xc0001a7f80, 0x1, 0x3)
	/workspace/philosopher/cmd/pipeline.go:77 +0x528
github.com/spf13/cobra.(*Command).execute(0x86cd460, 0xc0001a7f20, 0x3, 0x3, 0x86cd460, 0xc0001a7f20)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x86cdee0, 0x0, 0x0, 0x0)
/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:34 +0x2d
main.main()
	/workspace/philosopher/main.go:22 +0x6e
time="21:17:45" level=info msg="Executing Workspace  v3.2.3"
time="21:17:46" level=info msg="Removing workspace"
time="21:17:46" level=info msg=Done

**Comment by prvst** [comment]
@javanOkendo This is related to MSFragger, not Philosopher. It looks like you don't have enough memory. I'm transferring you to the MSFragger tracker.
