### ISSUE TITLE
Error in PeptideProphet via FragPipe when using custom enzyme 

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/philosopher#180]
I am using MSFragger 3.1.1, Philopher 3.4.13, and FragPipe 14.0 in Windows.

I am doing an open search and have digested my samples using a fairly uncommon enzyme (wild-type alpha-lytic protease, aka WALP; citation: 10.1074/mcp.M113.034710), which cleaves after TASV. In the MsFragger tab of FragPipe, I have selected "custom" for enzyme rules, entered "WALP" for enzyme name, and entered "TASV" for cut after. On the Validation tab of FragPipe, under PeptideProphet, i have entered:
--nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --enzyme WALP : cut(TASV) sense(C)

I got the following error:

INFO[17:04:56] Executing PeptideProphet  v3.4.13            
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >'
  what():  failed opening file: The filename, directory name, or volume label syntax is incorrect.​

: iostream error
FATA[17:04:58] Cannot execute program. There was an error with PeptideProphet, please check your parameters and input files 
Process 'PeptideProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

I am sure my syntax is wrong on the PeptideProphet command line, but I wanted to see if you could help. I've attached my log and parameter files. 

Thanks,
Josh

[fragger_params.txt](https://github.com/Nesvilab/philosopher/files/5876493/fragger_params.txt)
[fragpipe_2021-01-26_17-00-13_config.txt](https://github.com/Nesvilab/philosopher/files/5876494/fragpipe_2021-01-26_17-00-13_config.txt)
[log_2021-01-26_17-07-19.txt](https://github.com/Nesvilab/philosopher/files/5876495/log_2021-01-26_17-07-19.txt)
[shepherd_config.txt](https://github.com/Nesvilab/philosopher/files/5876496/shepherd_config.txt)
[umpire-se_2021-01-26_17-00-13_params.txt](https://github.com/Nesvilab/philosopher/files/5876497/umpire-se_2021-01-26_17-00-13_params.txt)

**Comment by prvst** [comment]
@anesvi In this case, do you think that PeptideProphet should be set with the nonspecific enzyme type?

**Comment by anesvi** [comment]
PeptideProphet can only recognized a number of predefined enzymes. So if you create a new enzyme name in MSFragger, it will crash philosopher

So yes, you can define a new set of cleavage rules in MSFragger, but put ‘nonspecific’ in the enzyme name field. Or, alternatively, add  --enzyme nonspecific
to PeptideProphet command in Validation tab. I think peptideprophet  will run fine, and you do not need to rerun MSFragger. Re-Start from Validation

Alexey

**Comment by jossmi** [comment]
Alexey and Felipe, thanks a ton!

**Comment by jossmi** [comment]
Hi, sorry to add another comment after this was closed - the "nonspecific" enzyme name in MSFragger and omitting any "--enzyme" note in PeptideProphet on the validation tab worked to get me through PrptideProphet. However, now I am getting an error with PTMShepherd:

Creating combined histogram
11:29:01.711 [main] WARN edu.umich.andykong.ptmshepherd.peakpicker.PeakSummary - Empty 'features' encountered
Exception in thread "main" java.lang.NullPointerException
	at edu.umich.andykong.ptmshepherd.peakpicker.ModSummary.toFile(ModSummary.java:104)
	at edu.umich.andykong.ptmshepherd.PTMShepherd.main(PTMShepherd.java:379)
Process 'PTMShepherd' finished, exit code: 1
Process returned non-zero exit code, stopping	Generated histogram file for dataset default-ptmshepherd-dataset [-2147483648 - -2147483648]


Any idea what's going on? I've attached my log file. With the exception of the enzyme settings, all the parameters are the same as what I attached before.

[log_2021-01-27_11-31-09.txt](https://github.com/Nesvilab/philosopher/files/5881992/log_2021-01-27_11-31-09.txt)

Thanks,
Josh

**Comment by prvst** [comment]
Hi @jossmi. Feel free to keep posting if necessary. I'll re-open the issue and move it to the FragPipe repository so others (including the person responsible for PTM-Shepherd) can help you too.
