### ISSUE TITLE
Update checked is not currently working

### ISSUE THREAD

**Issue by theoplatt** [Nesvilab/philosopher#198]
Running the workspace --init process fails on checking for updates. I suspect it has something to do with release tags?

To reproduce:

```
biodocker@fd0d2defe81d:/app$ philosopher workspace --init
INFO[16:13:25] Executing Workspace  v3.4.13                 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
philosopher/lib/gth.UpdateChecker(0xd21c40, 0x7, 0xd22560, 0xa)
        /workspace/philosopher/lib/gth/gth.go:55 +0x594
philosopher/lib/wrk.Run(0xd21c40, 0x7, 0xd22560, 0xa, 0x0, 0x0, 0x10000)
        /workspace/philosopher/lib/wrk/wrk.go:26 +0x2e6
philosopher/cmd.glob..func20(0x79b00e0, 0xc000331de0, 0x0, 0x1)
        /workspace/philosopher/cmd/workspace.go:26 +0xca
github.com/spf13/cobra.(*Command).execute(0x79b00e0, 0xc000331dd0, 0x1, 0x1, 0x79b00e0, 0xc000331dd0)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x79af660, 0x0, 0x0, 0x0)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
        /workspace/philosopher/cmd/root.go:35 +0x2d
main.main()
        /workspace/philosopher/main.go:22 +0x6e
biodocker@fd0d2defe81d:/app$ philosopher workspace --init --nocheck=true
INFO[16:13:33] Executing Workspace  v3.4.13                 
INFO[16:13:33] Creating workspace                           
INFO[16:13:33] Done                                         
biodocker@fd0d2defe81d:/app$ 

```

Thanks

**Comment by prvst** [comment]
This might be caused by a GitHub resource that is down. I'll investigate.

**Comment by ulo** [comment]
Hi,
we get the same error, Philosopher is currently not usable...
I think you have a great piece of software here for proteomics data analysis, but you do an update check to GitHub without any error handling? Really?

**Comment by ulo** [comment]
As a workaround, I blocked the failing update procedure by adding the following two lines to my local `/etc/hosts` file
```
0.0.0.0     api.github.com
::0         api.github.com
```
Philosopher is then running again.
But please remember to undo this change once the problem is fixed!

**Comment by prvst** [comment]
Hi. That was a problem with the GitHub interface. The issue should be resolved now. P{lease, don't change your system settings as this might affect other things. Thanks for reporting.
