### ISSUE TITLE
Workspace init error

### ISSUE THREAD

**Issue by limbo1996** [Nesvilab/philosopher#199]
**Describe the bug**
Commands run:
```
philosopher workspace --init
```
I got this error
```
INFO[10:54:20] Executing Workspace  v3.4.13                 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
philosopher/lib/gth.UpdateChecker(0xd21c40, 0x7, 0xd22560, 0xa)
        /workspace/philosopher/lib/gth/gth.go:55 +0x594
philosopher/lib/wrk.Run(0xd21c40, 0x7, 0xd22560, 0xa, 0x0, 0x0, 0x10000)
        /workspace/philosopher/lib/wrk/wrk.go:26 +0x2e6
philosopher/cmd.glob..func20(0x79b00e0, 0xc000220080, 0x0, 0x1)
        /workspace/philosopher/cmd/workspace.go:26 +0xca
github.com/spf13/cobra.(*Command).execute(0x79b00e0, 0xc000220070, 0x1, 0x1, 0x79b00e0, 0xc000220070)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x79af660, 0x0, 0x0, 0x0)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
        /workspace/philosopher/cmd/root.go:35 +0x2d
main.main()
        /workspace/philosopher/main.go:22 +0x6e
```
 The file structure of this directory
![](https://gitee.com/limbo1996/picgo/raw/master/png/20210413105721.png)

**Please complete the following information:**
 - OS: Windows WSL  Ubuntu 20.04 LTS

**Comment by o-t** [comment]
I got the same error too. I am using the latest version of philosopher v3.4.13, on a CentOS cluster

**Comment by avera1988** [comment]
Hi, we have the same issue: 
```
INFO[14:53:53] Executing Workspace  v3.4.13                 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
philosopher/lib/gth.UpdateChecker(0xd21c40, 0x7, 0xd22560, 0xa)
	/workspace/philosopher/lib/gth/gth.go:55 +0x594
philosopher/lib/wrk.Run(0xd21c40, 0x7, 0xd22560, 0xa, 0x0, 0x0, 0x10000)
	/workspace/philosopher/lib/wrk/wrk.go:26 +0x2e6
philosopher/cmd.glob..func20(0x79b00e0, 0xc000494020, 0x0, 0x1)
	/workspace/philosopher/cmd/workspace.go:26 +0xca
github.com/spf13/cobra.(*Command).execute(0x79b00e0, 0xc000494010, 0x1, 0x1, 0x79b00e0, 0xc000494010)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x79af660, 0x0, 0x3, 0x4)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x2d
main.main()
	/workspace/philosopher/main.go:22 +0x6e
```

It was solved by: the --nocheck flag for not checking the new versions:

./philosopher workspace --nocheck --clean

INFO[15:02:30] Executing Workspace  v3.4.13                 
INFO[15:02:30] Removing workspace                           
WARN[15:02:30] Cannot read file. open .meta/meta.bin: no such file or directory 
INFO[15:02:30] Done

**Comment by prvst** [comment]
Hi. That was a problem with the GitHub interface. The issue should be resolved now. Thanks for reporting.
