### ISSUE TITLE
ProteinProphet Error

### ISSUE THREAD

**Issue by uonnet** [Nesvilab/philosopher#261]
I am trying to run philosopher pipeline, but it stopped at the ProteinProphet step with an error
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: /tmp/78fe0bc2-455f-4e07-b5dc-669bf8426896/batchcoverage: No such file or directory
command "/tmp/78fe0bc2-455f-4e07-b5dc-669bf8426896/batchcoverage "/home/db/2021-08-10-decoys-custom_database_swissprot_trembl.fasta.fas" "/tmp/78fe0bc2-455f-4e07-b5dc-669bf8426896/interact.prot.xml.covinfo" "/tmp/78fe0bc2-455f-4e07-b5dc-669bf8426896/interact.prot.xml.cov"" failed with exit code 32512
time="01:54:26" level=fatal msg="Cannot read file. open /tmp/78fe0bc2-455f-4e07-b5dc-669bf8426896/interact.prot.xml: no such file or directory"
```
This is the whole log [o1011868.txt](https://github.com/Nesvilab/philosopher/files/6981596/o1011868.txt)

I hope that you can let me know how to fix this problem. Thanks!

**Comment by prvst** [comment]
Is that an HPC environment?

**Comment by uonnet** [comment]
Yes it is

**Comment by prvst** [comment]
It seems you don't have permission to access the temp folder, this is a common issue with shared HPC clusters or environments. Philosopher allows you to user alternative folders as a _tmp_, to do that, you have to add the flag **--temp** to the **workspace** command, and you pass the location you want to use.

**Comment by uonnet** [comment]
Sorry to reopen the issue, but this is the first time I saw this error. In the past there was no problem with philosopher. If I don't have permission to access the temp folder, I thought it will affect every analysis?

**Comment by prvst** [comment]
Yes, the temp folder is used in all analysis, and without permission, the programs will not run. I suggest contacting your system admin, since this is out of my reach.

**Comment by tobiasko** [comment]
I am having the same issue using version 4.8.1:

```
/scratch/tobiasko/software/fragpipe/tools/philosopher_v4.8.1_linux_amd64/philosopher workspace --init --temp /scratch/tobiasko/20230405/tmp
INFO[13:36:42] Executing Workspace  v4.8.1
INFO[13:36:43] Creating workspace
INFO[13:36:43] Done

/scratch/tobiasko/software/fragpipe/tools/philosopher_v4.8.1_linux_amd64/philosopher database --id UP000005640,UP000002032 --contam
INFO[13:36:51] Executing Database  v4.8.1
ERRO[13:36:51] Cannot write file. open /tmp/proteomes.csv: permission denied
panic: Cannot write file. open /tmp/proteomes.csv: permission denied

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xc000032b40, 0x3d}, {0xb379d5, 0x1?})
	/workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.WriteFile({0xca0fa0?, 0xc0002dd080?}, {0xb379d5, 0x5})
	/workspace/philosopher/lib/msg/msg.go:93 +0x6e
philosopher/lib/dat.GetOrganismID({0xb36e5e, 0x4}, {0x7ffd9fc0ee20, 0xb})
	/workspace/philosopher/lib/dat/dat.go:359 +0x216
philosopher/lib/dat.Run({{0xc00002c630, 0x24}, {0xc00002a660, 0x1a}, {0xc00002a680, 0x1e}, {0xc00002c660, 0x29}, {0xc00002a6a0, 0x20}, ...})
	/workspace/philosopher/lib/dat/dat.go:93 +0x930
philosopher/cmd.glob..func4(0x26108e0?, {0xb3726a?, 0x3?, 0x3?})
	/workspace/philosopher/cmd/database.go:23 +0x7e
github.com/spf13/cobra.(*Command).execute(0x26108e0, {0xc0002dced0, 0x3, 0x3})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x260f4c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90

```
Why is it still trying to write to /tmp/...?

**Comment by fcyu** [comment]
Seems to be similar to the other issue: https://github.com/Nesvilab/philosopher/issues/429#issuecomment-1497511875

Felipe @prvst , does Philosopher write prot,xml to temp directory but not the result folder?

Thanks,

Fengchao

**Comment by prvst** [comment]
Yes, the prot.xml file is written to the temp folder. You can change the temp location to a custom one using the --temp flag from workspace.

**Comment by prvst** [comment]
@tobiasko can you check if you have permission to write to tmp, and or if your tmp is full ? There are some secondary files that are needed, not too bug though.

**Comment by prvst** [comment]
Fixed. Added to v5.0.0 (Should be out soon!)

**Comment by fcyu** [comment]
Hi @prvst and @anesvi ,

As we discussed yesterday, should we send the fixed version to @tobiasko , and let him help to test if it is good?

Thanks,

Fengchao

**Comment by tobiasko** [comment]
I am happy to help!
