### ISSUE TITLE
Index out of range with first pass only coupled with 10-plex TMT

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#31]
Hi Felipe,

There may be a bug under first pass only coupled with 10-plex TMT setting. Under 2D filtering, there is no error. 

Following are the commands:
```shell
philosopher_windows_amd64.exe workspace --clean
philosopher_windows_amd64.exe workspace --init
philosopher_windows_amd64.exe database --annotate some.fasta --prefix DECOY_
philosopher_windows_amd64.exe peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --decoy DECOY_ --combine --database some.fasta *_c.pepXML
philosopher_windows_amd64.exe proteinprophet --maxppmdiff 1000000 interact.pep.xml
philosopher_windows_amd64.exe filter --sequential --razor --mapmods --tag DECOY_ --pepxml interact.pep.xml
philosopher_windows_amd64.exe labelquant --plex 10 --purity 0 --dir C:\some\
philosopher_windows_amd64.exe report
```

Following are the console output of `philosopher_windows_amd64.exe report':
```shell
INFO[15:12:07] Executing Report 20190206
INFO[15:12:30] Creating TMT PSM report
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/prvst/philosopher/lib/rep.Run(0xc0000806f0, 0x24, 0xc0001321c0, 0x6d, 0xc00009e500, 0x49, 0xc00009c580, 0x7c, 0xc00009c600, 0x73, ...)
        /home/prvst/go/src/github.com/prvst/philosopher/lib/rep/rep.go:340 +0xa8d
github.com/prvst/philosopher/cmd.glob..func14(0x2de3760, 0x2e06688, 0x0, 0x0)
        /home/prvst/go/src/github.com/prvst/philosopher/cmd/report.go:28 +0x104
github.com/spf13/cobra.(*Command).execute(0x2de3760, 0x2e06688, 0x0, 0x0, 0x2de3760, 0x2e06688)
        /home/prvst/go/src/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0x2de39c0, 0x2de3e80, 0xc000093f68, 0xc000093f88)
        /home/prvst/go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0x2de39c0, 0x1, 0x2de3e80)
        /home/prvst/go/src/github.com/spf13/cobra/command.go:800 +0x32
github.com/prvst/philosopher/cmd.Execute()
        /home/prvst/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x34
main.main()
        /home/prvst/go/src/github.com/prvst/philosopher/main.go:19 +0x75
```

Thanks,

Fengchao

**Comment by prvst** [comment]
fixed
