### ISSUE TITLE
${PHILOSOPHER} database --custom  and --add option do not work

### ISSUE THREAD

**Issue by cpanse** [Nesvilab/philosopher#374]
**Describe the bug**

We try to use --custom and --add option together (because see my next issue). 

and get
```
panic: runtime error: index out of range [2] with length 0
```

Is that supposed to work? 

**To Reproduce**

```
#!/bin/bash

set -euxo pipefail
TMPDIR=$PWD
TMP=$TMPDIR
TEMP=$TMPDIR

export TMPDIR TMP TEMP

export JAVA_OPTS=-Djava.io.tmpdir=$PWD

#PHILOSOPHER=/usr/local/nesvilab/philosopher_v4.3.0/philosopher-v4.3.0-RC
PHILOSOPHER=/usr/local/nesvilab/philosopher_v4.5.1/philosopher-v4.5.1-RC5
${PHILOSOPHER} version
${PHILOSOPHER} workspace --temp $PWD
${PHILOSOPHER} workspace --clean
${PHILOSOPHER} workspace --init

${PHILOSOPHER} database --custom /misc/fasta/fgcz_9606_reviewed_cnl_20220429.fasta --add /scratch/FRAGPIPE/WU279891/spikein.fasta
```

OUTPUT
```
cpanse@fgcz-c-073:/scratch/cpanse/philosopher > bash runme.bash 
+ TMPDIR=/scratch/cpanse/philosopher
+ TMP=/scratch/cpanse/philosopher
+ TEMP=/scratch/cpanse/philosopher
+ export TMPDIR TMP TEMP
+ export JAVA_OPTS=-Djava.io.tmpdir=/scratch/cpanse/philosopher
+ JAVA_OPTS=-Djava.io.tmpdir=/scratch/cpanse/philosopher
+ PHILOSOPHER=/usr/local/nesvilab/philosopher_v4.5.1/philosopher-v4.5.1-RC5
+ /usr/local/nesvilab/philosopher_v4.5.1/philosopher-v4.5.1-RC5 version
INFO[11:45:28] Current Philosopher build and version         build=202207271218 version=v4.5.1
+ /usr/local/nesvilab/philosopher_v4.5.1/philosopher-v4.5.1-RC5 workspace --temp /scratch/cpanse/philosopher
INFO[11:45:29] Executing Workspace  v4.5.1                  
INFO[11:45:29] Done                                         
+ /usr/local/nesvilab/philosopher_v4.5.1/philosopher-v4.5.1-RC5 workspace --clean
INFO[11:45:29] Executing Workspace  v4.5.1                  
INFO[11:45:29] Removing workspace                           
INFO[11:45:29] Done                                         
+ /usr/local/nesvilab/philosopher_v4.5.1/philosopher-v4.5.1-RC5 workspace --init
INFO[11:45:29] Executing Workspace  v4.5.1                  
INFO[11:45:29] Creating workspace                           
INFO[11:45:29] Done                                         
+ /usr/local/nesvilab/philosopher_v4.5.1/philosopher-v4.5.1-RC5 database --custom /misc/fasta/fgcz_9606_reviewed_cnl_20220429.fasta --add /scratch/FRAGPIPE/WU279891/spikein.fasta
INFO[11:45:29] Executing Database  v4.5.1                   
WARN[11:45:29] contaminants are not going to be added to database 
INFO[11:45:29] Generating the target-decoy database         
INFO[11:45:30] Creating file                                
panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
philosopher/lib/dat.ProcessUniProtKB({0xc00091ae41, 0x3a}, {0xc000433290, 0x86}, {0xb30a8c, 0x4})
        /workspace/philosopher/lib/dat/db.go:278 +0x952
philosopher/lib/dat.(*Base).ProcessDB(0xc000440000, {0xc003045620, 0x57}, {0xb30a8c, 0x4})
        /workspace/philosopher/lib/dat/dat.go:144 +0x1bb
philosopher/lib/dat.Run({{0xc0002266f0, 0x24}, {0xc0002704c0, 0x1b}, {0xc000226720, 0x29}, {0xc000226750, 0x2a}, {0xc000226780, 0x21}, ...})
        /workspace/philosopher/lib/dat/dat.go:117 +0x6d0
philosopher/cmd.glob..func4(0x2071a40?, {0xb30958?, 0x4?, 0x4?})
        /workspace/philosopher/cmd/database.go:23 +0x7e
github.com/spf13/cobra.(*Command).execute(0x2071a40, {0xc000302f80, 0x4, 0x4})
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x20707e0)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
philosopher/cmd.Execute()
        /workspace/philosopher/cmd/root.go:35 +0x25
main.main()
        /workspace/philosopher/main.go:25 +0x90
cpanse@fgcz-c-073:/scratch/cpanse/philosopher > 

```

to get an idea of the FASTA

```
cpanse@fgcz-c-073:/scratch/cpanse/philosopher > head /misc/fasta/fgcz_9606_reviewed_cnl_20220429.fasta /scratch/FRAGPIPE/WU279891/spikein.fasta
==> /misc/fasta/fgcz_9606_reviewed_cnl_20220429.fasta <==
>aa|fgcz_9606_reviewed_cnl|2022-04-29 reviewed sequences for human from uniprot https://www.uniprot.org/uniprot/?query=*&fil=reviewed%3Ayes+AND+organism%3A%22Homo+sapiens+%28Human%29+%5B9606%5D%22+AND+proteome%3Aup000005640
CRAPCRAPCRAP
>sp|P51451|BLK_HUMAN Tyrosine-protein kinase Blk OS=Homo sapiens OX=9606 GN=BLK PE=1 SV=3
MGLVSSKKPDKEKPIKEKDKGQWSPLKVSAQDKDAPPLPPLVVFNHLTPPPPDEHLDEDK
HFVVALYDYTAMNDRDLQMLKGEKLQVLKGTGDWWLARSLVTGREGYVPSNFVARVESLE
MERWFFRSQGRKEAERQLLAPINKAGSFLIRESETNKGAFSLSVKDVTTQGELIKHYKIR
CLDEGGYYISPRITFPSLQALVQHYSKKGDGLCQRLTLPCVRPAPQNPWAQDEWEIPRQS
LRLVRKLGSGQFGEVWMGYYKNNMKVAIKTLKEGTMSPEAFLGEANVMKALQHERLVRLY
AVVTKEPIYIVTEYMARGCLLDFLKTDEGSRLSLPRLIDMSAQIAEGMAYIERMNSIHRD
LRAANILVSEALCCKIADFGLARIIDSEYTAQEGAKFPIKWTAPEAIHFGVFTIKADVWS

==> /scratch/FRAGPIPE/WU279891/spikein.fasta <==
>sp|ADD001|PF3D7_1335000 MSRP1
MKRQIILFTSLFIFSLNLTLSYEKSNNRLGYYNEENADNKEKNKITFMFNDIKVGMQNDVEENLDNGKNVLEDEHLVIGQEGQTDNEGPHTETKPERSVESGGTGDSVSNHESELPRDTETREVVTTVQPGTQLGESGAKETLESQTSPAPQGTSGLQGEKVPGALSSVSQTSSPDVSSRSEQPQTMPESPRPEGTSTESQPRGSTESDASNKNGSQTNVRTISNSSNSITSPQTTQPSNNQNNTVSTTSEVKYLDLLYDELLTNSEGKHQVHFGENHKKYNIFRKHYDNFVINQKEYDIIKKLLNSIFRDNNENEKMKNLVSIFQKALNDKKFHDQFKNFIYGIYGFAKRHSYLRNEKIQNDSEYKEFFENAVDLLNTL
>sp|ADD002|PF3D7_1334800 MSRP2
MKGQAIYFVFVFLYFLNCVGCNSKNNNKRTSYNKKKENLKNFDNIVLDDFYSAFDSQDNYESKLKKNEDDIIGQGIFSLISKKNQEKEKSLKGESEDNTKLQVTKVQGAQVDQAVEPLEKSPEDENKEIPTLDSPQNGNPTSYTSNLSTPPLKRMDEVFDDVLKHLNKEDKVVTDENKNKYNEFKKEFDIFTMNVSEYEIMKNLLITFSKKIDENNQIQTKIENIFNKALKDNKYKEQFKNFIYGLYSFAKRHNYLIVNKTNDTTLHKDLFENALNLINTI
>sp|P42212|GFP_AEQVI Green fluorescent protein OS=Aequorea victoria OX=6100 GN=GFP PE=1 SV=1
MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK
>sp|AD003|iRT-Kit_WR_fusion iRT-Kit_WR_fusion GN=iRTKit
LGGNEQVTRYILAGVENSKGTFIIDPGGVIRGTFIIDPAAVIRGAGSSEPVTGLDAKTPVISGGPYEYRVEATFGVDESNAKTPVITGAPYEYRDGLDAASYYAPVRADVTPADFSEWSKLFLQFGAQGSPFLK

```

**Expected behavior**

the call should concatenate both FASTAs.

**Please complete the following information:**

 ```
cpanse@fgcz-c-073:/scratch/cpanse/philosopher > uname -a 
Linux fgcz-c-073 5.4.121-0504121-generic #202105220633 SMP Sat May 22 10:38:55 UTC 2021 x86_64 GNU/Linux
```

 ```
cpanse@fgcz-c-073:/scratch/cpanse/philosopher > /usr/local/nesvilab/philosopher_v4.5.1/philosopher-v4.5.1-RC5 version
INFO[11:50:21] Current Philosopher build and version         build=202207271218 version=v4.5.1
```

thank you!

**Comment by cpanse** [comment]
@prvst 
@tobiasko

caused by a wrong formatted input

`sp|AD003|iRT-Kit_WR`

Whatsoever a warning that the format is not correct would be a nice feature. (or have I overseen something?)
