### ISSUE TITLE
philosopher-v4.5.1-RC5 seems to break tmt-integrator-3.3.3.jar and TMTIntegrator_v4.0.1.jar

### ISSUE THREAD

**Issue by cpanse** [Nesvilab/philosopher#378]
**Describe the bug**

philosopher-v4.5.1-RC5 breaks tmt-integrator-3.3.3.jar and TMTIntegrator_v4.0.1.jar

**To Reproduce**

```
/usr/local/nesvilab/fragpipe/bin/fragpipe --headless --workflow /scratch/cpanse/TMT/TMT_test_data_singleFile_FStein/FragPipe_workflow.workflow --manifest /scratch/cpanse/TMT/TMT_test_data_singleFile_FStein/manifest.fp-manifest --workdir /scratch/cpanse/TMT/TMT_test_data_singleFile_FStein --config-msfragger /usr/local/nesvilab/MSFragger-3.5/MSFragger-3.5.jar --config-philosopher /usr/local/nesvilab/philosopher_v4.4.0 --ram 128 \
  2>2.log.txt 1>1.log.txt
```

works!

using philosopher-v4.5.1-RC5  I get errors as:

```
java -Xmx128G -cp /usr/local/nesvilab/FragPipe-18.0/tools/tmt-integrator-3.3.3.jar TMTIntegrator /scratch/FRAGPIPE/P28644/tmt-integrator-conf.yml /scratch/FRAGPIPE/P28644/TMT10plex_T1_2/psm.tsv /scratch/FRAGPIPE/P28644/TMT10plex_T3_4/psm.tsv
TMT-Integrator v3.3.3
Exception in thread "main" java.lang.NumberFormatException: For input string: "true"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:543)
        at TMTIntegrator.UpdateColumns(TMTIntegrator.java:642)
        at TMTIntegrator.main(TMTIntegrator.java:51)
Process 'TmtIntegrator' finished, exit code: 1
Process returned non-zero exit code, stopping
```

**Expected behavior**

using philosopher-v4.5.1-RC5   should make TMTIntegrator work as with philosopher_v4.4.0.

**Please complete the following information:**

 -docker debian:11
 
**Additional context**

it was like searching for a phantom for two days  ... thanks to @wolski and @fstein

**Comment by prvst** [comment]
Hi Christian, I have already changed the code. Please grab the latest (pre-release) version from Dropbox. Keep in mind that you are working with unstable versions, so hiccups are expected.

Cheers.

**Comment by hsiaoyi0504** [comment]
Just for future refrence, philosopher-v4.5.1-RC20 seems not work with tmt-integrator-3.3.3.jar, TMTIntegrator_v4.0.2.jar, and TMTIntegrator_v4.0.4.jar.
