### ISSUE TITLE
`prot.xml` was written to the temp directory but not the result directory, which resulted in the incomplete file and crashed the filter command

### ISSUE THREAD

**Issue by ohickl** [Nesvilab/philosopher#429]
Hi,

I am running some tests on linux with a large database built from multiple metagenomes. It crashes at the filtering step with:
```
...
time="02:21:03" level=error msg="Cannot decode packed binary. XML syntax error on line 361982260: unexpected EOF"
panic: Cannot decode packed binary. XML syntax error on line 361982260: unexpected EOF

goroutine 1 [running]:
philosopher/lib/msg.callLogrus({0xcab9050320, 0x4f}, {0xb379d5, 0x1?})
        /workspace/philosopher/lib/msg/msg.go:319 +0x354
philosopher/lib/msg.DecodeMsgPck({0xca0640?, 0xc73993a168?}, {0xb379d5, 0x5})
        /workspace/philosopher/lib/msg/msg.go:120 +0x6e
philosopher/lib/spc.(*ProtXML).Parse(0xc002a55910, {0x7fffb4eaa687, 0x62})
        /workspace/philosopher/lib/spc/spc.go:97 +0x210
philosopher/lib/id.(*ProtXML).Read(0xc002a55bb8, {0x7fffb4eaa687?, 0xc0002b5b90?})
        /workspace/philosopher/lib/id/pro.go:116 +0x85
philosopher/lib/fil.ReadProtXMLInput({0x7fffb4eaa687?, 0xd?}, {0x7fffb4eaa617, 0x4}, 0x3ff0000000000000)
        /workspace/philosopher/lib/fil/fil.go:504 +0x9f
philosopher/lib/fil.Run({{0xc0000288a0, 0x24}, {0xc00002c8a0, 0x57}, {0xc0000288d0, 0x29}, {0xc0000fe3f0, 0x66}, {0xc00002c900, 0x5d}, ...})
        /workspace/philosopher/lib/fil/fil.go:81 +0x77a
philosopher/cmd.glob..func5(0x2610bc0?, {0xb3726a?, 0xa?, 0xa?})
        /workspace/philosopher/cmd/filter.go:43 +0x390
github.com/spf13/cobra.(*Command).execute(0x2610bc0, {0xc000286b40, 0xa, 0xa})
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x260f4c0)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
        /workspace/philosopher/cmd/root.go:35 +0x25
main.main()
        /workspace/philosopher/main.go:25 +0x90
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 5 remaining tasks
```

The command is:
```
${fragpipe_bin} --headless \
                --workflow ${fragpipe_dir}/workflows/LFQ-MBR_template.workflow \
                --manifest ${fragpipe_dir}/workflows/template.fp-manifest \
                --workdir ${db_dir}/sample_01_fragpipe_test_closed_all_samp_db_01 \
                --ram 1700 \
                --threads 60 \
                --config-msfragger ${msfragger_bin} \
                --config-ionquant ${ionquant_bin} \
                --config-philosopher ${phil_bin} \
                --config-python ${CONDA_PREFIX}/bin/python3.10 > sample_01_fragpipe_test_closed_all_samp_db_01.log 2>&1
```

I assume, this might be what @anesvi mentioned before: https://github.com/Nesvilab/philosopher/discussions/427#discussioncomment-5381192? 

Also, it never seemed to actually go much beyond the memory requirements reported per database slice for the fragments to be searched (e.g. ~120G). It did crash though, if I decreased the number of slices to e.g. 20 from 25. Is this because it hits the limit for the number of elements in the index? Ideally, I would like to have as few db slices as possible and use more of the available memory. I did not log the memory consumption though, so it might be that I just missed a large spike.

Best

Oskar

[sample_01_fragpipe_test_closed_all_samp_db_01.log](https://github.com/Nesvilab/FragPipe/files/11108906/sample_01_fragpipe_test_closed_all_samp_db_01.log)

**Comment by prvst** [comment]
Yes, the prot.xml file is written to the temp folder. You can change the temp location to a custom one using the --temp flag from workspace.

**Comment by fcyu** [comment]
Thanks @prvst . This also explains the error in https://github.com/Nesvilab/FragPipe/issues/807#issuecomment-1303625410

Best,

Fengchao

**Comment by prvst** [comment]
The prot.xml file is written to the temp folder. You can change the temp location to a custom one using the --temp flag from workspace.
