### ISSUE TITLE
Problem installing philosopher for Fragpipe 20.0

### ISSUE THREAD

**Issue by tobimaile** [Nesvilab/philosopher#437]
Hi guys!

I tried to install the new version and with philosopher following error message showing up:

java.lang.IllegalStateException: Error downloading Philosopher automatically
	at com.dmtavt.fragpipe.tabs.TabConfig.lambda$actionPhilosopherDownload$26(TabConfig.java:1186)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\fragpipe\lib\..\tools\philosopher_v5.0.0_windows_amd64\philosopher_v5.0.0_windows_amd64\License (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at com.github.chhh.utils.ZipUtils.unzip(ZipUtils.java:89)
	at com.dmtavt.fragpipe.tools.philosopher.Philosopher.downloadPhilosopherAutomatically(Philosopher.java:294)
	at com.dmtavt.fragpipe.tabs.TabConfig.lambda$actionPhilosopherDownload$26(TabConfig.java:1184)
	... 1 more

Best,
Tobi

**Comment by fcyu** [comment]
Hi Tobi,

You are so fast! We have been aware of it and are working on it now.

Best,

Fengchao

**Comment by tobimaile** [comment]
I literally tried to start an MSFRagger run a mere 13 minutes after you uploaded it on GitHub.

We are not watching you, I promise!
;)

**Comment by fcyu** [comment]
Hi Tobi,

Yamei @AimeeD90 fixed the issue.

Best,

Fengchao

**Comment by tobimaile** [comment]
That was really fast as well! I have another one though regarding database add-on of decoys and contaminants:

java.lang.IllegalStateException: Something happened during database update
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:376)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:296)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:372)
	... 1 more

**Comment by fcyu** [comment]
I couldn't reproduce this one:
![image](https://github.com/Nesvilab/philosopher/assets/6926299/da100776-ccc3-4389-97f4-90ed79bba8b1)

Could you share the messages in the `Console` of the `Run` tab?

Thanks,

Fengchao

**Comment by tobimaile** [comment]
16:35:14 INFO : Executing: C:\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe workspace --init --nocheck --temp C:\Users\tmaile\AppData\Local\Temp\3fda4d7d-8ee3-49fc-bc68-2abd7b5193a0
16:35:14 INFO : Process output: 
16:35:14 INFO : Executing: C:\fragpipe\tools\philosopher_v5.0.0_windows_amd64\philosopher.exe database --custom S:\Data_Analysis\FASTA-Files\FASTA_Tobi\Uniprot589_Mouse_humanNRAS_WT_Q61R_040423.fasta --contam --contamprefix
16:35:14 INFO : Process output: 
16:35:14 ERROR: Something happened during database update
java.lang.IllegalStateException: Process returned non zero value
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:296)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$updateDb$7(DownloadDbHelper.java:372)
	at java.base/java.lang.Thread.run(Unknown Source)
16:35:14 INFO : No more file events when updating database

**Comment by fcyu** [comment]
Hmm, could you share `Uniprot589_Mouse_humanNRAS_WT_Q61R_040423.fasta` with us, or point the location to download it.

Thanks,

Fengchao

**Comment by tobimaile** [comment]
Hi, just wanted to update you: I ran the same fasta file on a local desktop folder and adding contaminants and decoys worked. Adding the edited fasta file to the server location and loading it from there worked as well. It could be a permissions issue with our local server, Fragpipe trying to save the edited fasta file but failing thus causing these issues. 
I have someone looking into it. Workaround for us for now is to run fasta building on the desktop. I will update you in case this isn't the issues and/or we run into more problems.
