### ISSUE TITLE
Index out of range when there is no PSM from the first pass.

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/philosopher#46]
Hi Felipe,

I think I just triggered a bug caused by no PSM case after the first pass. Following is the log

```bash
+ philosophe filter --sequential --razor --mapmods --models --tag rev_ --pepxml ./interact.pep.xml --protxml ./interact.prot.xml
time="16:22:21" level=info msg="Executing Filter 20190301"
time="16:22:21" level=info msg="Processing peptide identification files"
time="16:22:28" level=info msg="Printing models"
time="16:22:31" level=info msg="1+ Charge profile" decoy=0 target=0
time="16:22:31" level=info msg="2+ Charge profile" decoy=13316 target=46197
time="16:22:31" level=info msg="3+ Charge profile" decoy=3784 target=11451
time="16:22:31" level=info msg="4+ Charge profile" decoy=408 target=1543
time="16:22:31" level=info msg="5+ Charge profile" decoy=148 target=359
time="16:22:31" level=info msg="6+ Charge profile" decoy=0 target=0
time="16:22:32" level=info msg="Database search results" ions=52891 peptides=49548 psms=77206
time="16:22:32" level=info msg="Converged to 0.00 % FDR with 0 PSMs" decoy=0 threshold=10 total=0
time="16:22:32" level=info msg="Converged to 0.00 % FDR with 0 Peptides" decoy=0 threshold=10 total=0
time="16:22:32" level=info msg="Converged to 0.00 % FDR with 0 Ions" decoy=0 threshold=10 total=0
time="16:22:35" level=info msg="Protein inference results" decoy=8801 target=11444
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/prvst/philosopher/lib/fil.ProtXMLFilter(0x0, 0x0, 0x7ffd1ebc15d1, 0x4, 0xc002d60000, 0x47af, 0x5733, 0xc00401ade0, 0xc, 0x3f847ae147ae147b, ...)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/fil/fil.go:1069 +0x1d55
github.com/prvst/philosopher/lib/fil.processProteinIdentifications(0x0, 0x0, 0x7ffd1ebc15d1, 0x4, 0xc002d60000, 0x47af, 0x5733, 0xc00401ade0, 0xc, 0x3f847ae147ae147b, ...)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/fil/fil.go:593 +0x337
github.com/prvst/philosopher/lib/fil.Run(0xc000024630, 0x24, 0xc00002e480, 0x51, 0xc000024660, 0x29, 0xc00002e4e0, 0x60, 0xc00002e540, 0x57, ...)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/fil/fil.go:55 +0xee6
github.com/prvst/philosopher/cmd.glob..func5(0x3e9d5e0, 0xc0001dcb40, 0x0, 0xa)
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/filter.go:55 +0x1f8
github.com/spf13/cobra.(*Command).execute(0x3e9d5e0, 0xc0001dca00, 0xa, 0xa, 0x3e9d5e0, 0xc0001dca00)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x3e9f260, 0x3e9f720, 0xc0001b9f68, 0xc0001b9f88)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x3e9f260, 0x1, 0x3e9f720)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/prvst/philosopher/cmd.Execute()
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x2d
main.main()
	/home/prvst/go/src/github.com/prvst/philosopher/main.go:19 +0x6e
```

Thanks,

Fengchao

**Comment by prvst** [comment]
fixed, thanks
