### ISSUE TITLE
ERRO[11:53:33] the protein FDR filter didn't reach the desired threshold, try a higher threshold using the --prot parameter 

### ISSUE THREAD

**Issue by Luc2702** [Nesvilab/philosopher#493]
[log_2024-05-14_11-54-23.txt](https://github.com/Nesvilab/FragPipe/files/15306589/log_2024-05-14_11-54-23.txt)

Hello,

I am trying to perform label-free quantification with LFQ-MBR on mzML converted files. I am getting an error regarding FDR threshold.
Would you have any idea how to fix this issue ? I have attached the log report.

Thanks for your help!

**Comment by pushomix** [comment]
My friend encountered the same issue and found these discussions particularly helpful. Below is the traceback of the final lines of the error:

`panic: the protein FDR filter didn't reach the desired threshold, try a higher threshold using the --prot parameter

goroutine 1 [running]:
github.com/Nesvilab/philosopher/lib/msg.callLogrus({0xc000310ee0, 0x6c}, {0xdec9af?, 0x1?})
/mnt/g/Dropbox/code/philosopher/lib/msg/msg.go:327 +0x2d8
github.com/Nesvilab/philosopher/lib/msg.Custom({0xf56e60?, 0xc001840220?}, {0xdec9af, 0x5})
/mnt/g/Dropbox/code/philosopher/lib/msg/msg.go:15 +0x68
github.com/Nesvilab/philosopher/lib/fil.ProtXMLFilter({{0x0, 0x0}, {0xc00000a158, 0x4}, {0xc003b2c7a0, 0x1a}, {0xc0077ba000, 0x4adb, 0x5b33}}, 0x3f847ae147ae147b, ...)
/mnt/g/Dropbox/code/philosopher/lib/fil/fdr.go:548 +0x8e5
github.com/Nesvilab/philosopher/lib/fil.ProcessProteinIdentifications({{0x0, 0x0}, {0xc00000a158, 0x4}, {0xc003b2c7a0, 0x1a}, {0xc0077ba000, 0x4adb, 0x5b33}}, 0x0?, ...)
/mnt/g/Dropbox/code/philosopher/lib/fil/fil.go:670 +0x5eb
github.com/Nesvilab/philosopher/lib/fil.Run({{0xc00001c690, 0x24}, {0xc00001c6c0, 0x27}, {0xc000024410, 0x45}, {0xc00001e680, 0x36}, {0xc00001c6f0, 0x2d}, ...})
/mnt/g/Dropbox/code/philosopher/lib/fil/fil.go:97 +0xb06
github.com/Nesvilab/philosopher/cmd.glob..func5(0xc00013a500?, {0xdec35c?, 0x4?, 0xdec360?})
/mnt/g/Dropbox/code/philosopher/cmd/filter.go:47 +0x4b7
github.com/spf13/cobra.(*Command).execute(0x2a22180, {0xc0000c00b0, 0xb, 0xb})
/mnt/g/Dropbox/code/philosopher/vendor/github.com/spf13/cobra/command.go:920 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x2a24120)
/mnt/g/Dropbox/code/philosopher/vendor/github.com/spf13/cobra/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
/mnt/g/Dropbox/code/philosopher/vendor/github.com/spf13/cobra/command.go:968
github.com/Nesvilab/philosopher/cmd.Execute()
/mnt/g/Dropbox/code/philosopher/cmd/root.go:35 +0x1a
main.main()
/mnt/g/Dropbox/code/philosopher/main.go:23 +0x85
ERRO[12:38:47] the protein FDR filter didn't reach the desired threshold, try a higher threshold using the --prot parameter
Process 'PhilosopherFilter' finished, exit code: 2
Process returned non-zero exit code, stopping` 

As suggested by tongyi.ai, possible solutions would be:
Certainly! Here’s a concise version in English:

---

### Steps to Resolve the Protein FDR Filter Issue

1. **Understand the Error**:
   - The error message `The protein FDR filter did not reach the desired threshold` means that the filtering process did not meet the specified quality control standards.

2. **Increase the FDR Threshold**:
   - Try using a higher FDR threshold with the `--prot` parameter. For example:
     ```bash
     philosopher filter --prot 0.05
     ```
   - Gradually increase this value until you find an acceptable balance between sensitivity and specificity.

3. **Check Input Data**:
   - Ensure your ProtXML files and other inputs are correctly formatted and of good quality.
   - Preprocess data to remove low-quality spectra or duplicates if necessary.

4. **Optimize Analysis Workflow**:
   - Review and adjust other parameters that might affect identification results, such as enzyme rules or modification types.
   - Ensure you are using the latest version of Philosopher for any improvements or bug fixes.

5. **Consult Documentation and Community**:
   - Refer to the official Philosopher documentation for detailed parameter explanations.
   - Check user forums or GitHub Issues for similar problems and solutions.

6. **Contact Support**:
   - If issues persist, contact Philosopher support with detailed logs and input samples for further assistance.

### Example Command:
```bash
philosopher filter --prot 0.05 --input your_input_file.prot.xml --output filtered_output_file.prot.xml
```

As a biologist, she has already obtained search results from alternative software tools. I recommend that she proceed with the biological validation of these results while we await the resolution of this issue🙂.
