### ISSUE TITLE
Database - cannot download redundant proteomes or in-house - java.lang error

### ISSUE THREAD

**Issue by Althalis** [Nesvilab/philosopher#514]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
I cannot even run so there's no log file.
Error message:
java.lang.IllegalStateException: Something happened during database download
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$downloadDb$4(DownloadDbHelper.java:169)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.dmtavt.fragpipe.process.ProcessResult.start(ProcessResult.java:55)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.runProcesses(DownloadDbHelper.java:271)
	at com.dmtavt.fragpipe.api.DownloadDbHelper.lambda$downloadDb$4(DownloadDbHelper.java:166)
	... 1 more

**- Describe the issue or question:**
Dear ragpipe team, 
I am trying to analyse data from a bacteria Rhodococcus q.  I went to the Database tab and Clicked 'Download'.
There's no reviewed sequences so I unchecked this requirement.
I selected Other and paster the UP number.
For the biggest two proteomes (flagged as redundant), i.e. UP000182683 or UP000053129 , I get the above error message in the download lo window.
But not for UP001217325.
https://www.uniprot.org/proteomes?dir=descend&query=%28organism_id%3A334542%29&sort=protein_count

I also get the message when trying to spike-in my own in-house fasta.

Questions:
- can we not use proteomes flagged as redundant?
- can you confirm that the way to use ONLY an in-house fasta is to select 'Other' without typing any UP number, and of course linking the fasta in the field at the bottom of the window?
- I suspect something is wrong in my fasta formatting since I get the above error. Any recommendation to correct this? (it was parsing fine in DIA-NN FYI so I expected it would parse ok here,but I might be missing something).

Thank you!

**Comment by fcyu** [comment]
I have reproduced the error

```shell
λ G:\bin\FragPipe-22.0\fragpipe\tools\Philosopher\philosopher-v5.1.1.exe database --contam --contamprefix --id UP000182683
time="11:16:20" level=info msg="Executing Database  v5.1.1"
C:\Users\yufe\AppData\Local\Temp\701bd00b-6be1-4f27-91a0-cca502240790\proteomes.csv
time="11:16:21" level=info msg="Fetching Rhodococcus qingshengii database UP000182683"
time="11:16:21" level=error msg="Cannot read file. please check if your parameters are correct, including the Uniprot ID"
```

Let me transferred it to https://github.com/Nesvilab/philosopher

> can we not use proteomes flagged as redundant?

I think we can unless there is a bug in Philosopher

> can you confirm that the way to use ONLY an in-house fasta is to select 'Other' without typing any UP number, and of course linking the fasta in the field at the bottom of the window?

You can provide your custom target-only fasta file and click "add decoys".

> I suspect something is wrong in my fasta formatting since I get the above error. Any recommendation to correct this? (it was parsing fine in DIA-NN FYI so I expected it would parse ok here,but I might be missing something).

I am not sure if it was due to your custom fasta file because I also couldn't download UP000182683 without providing any additional custom fasta file.

Best,

Fengchao
