### ISSUE TITLE
Error when working with big datatbase size

### ISSUE THREAD

**Issue by FantacticMisterFox** [Nesvilab/philosopher#54]
I get the following output when I try to use a custom database with the size of 167 Mb.
I do not run out of RAM.
Can I use philosopher with this database size?

```
INFO[13:42:21] Executing Database 20190418                  
WARN[13:42:21] Contaminants are not going to be added to database 
INFO[13:42:21] Processing decoys                            
INFO[13:43:07] Creating file                                
runtime: out of memory: cannot allocate 258760704-byte block (3474620416 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x865e571, 0xd)
	/usr/local/go/src/runtime/panic.go:608 +0x6a
runtime.largeAlloc(0xf6c6000, 0x8090001, 0xf7701360)
	/usr/local/go/src/runtime/malloc.go:1021 +0x107
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:914 +0x39
runtime.systemstack(0x110a57a0)
	/usr/local/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_386.s:357 fp=0x10d94d18 sp=0x10d94d14 pc=0x8094ec0
runtime.mallocgc(0xf6c6000, 0x8635c40, 0x1, 0x0)
	/usr/local/go/src/runtime/malloc.go:913 +0x6a0 fp=0x10d94d6c sp=0x10d94d18 pc=0x8051e70
runtime.growslice(0x8635c40, 0xd3800000, 0x20e700, 0x20e700, 0x20e701, 0x4, 0x1f9304b1, 0x29)
	/usr/local/go/src/runtime/slice.go:204 +0x117 fp=0x10d94dac sp=0x10d94d6c pc=0x8082937
github.com/prvst/philosopher/lib/dat.(*Base).ProcessDB(0x10da54c0, 0x2b6a6500, 0x4d, 0x86595ed, 0x4, 0x86595ed)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/dat/dat.go:153 +0x44f fp=0x10d95248 sp=0x10d94dac pc=0x8401bef
github.com/prvst/philosopher/lib/dat.Run(0x10cda360, 0x24, 0x10cda390, 0x2b, 0x10cda3c0, 0x29, 0x10cd0480, 0x3a, 0x10cd04c0, 0x31, ...)
	/home/prvst/go/src/github.com/prvst/philosopher/lib/dat/dat.go:89 +0x2c0 fp=0x10d9531c sp=0x10d95248 pc=0x84012d0
github.com/prvst/philosopher/cmd.glob..func4(0x1036da60, 0x10ce8760, 0x0, 0x2)
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/database.go:21 +0x101 fp=0x10d95e8c sp=0x10d9531c pc=0x852cdd1
github.com/spf13/cobra.(*Command).execute(0x1036da60, 0x10ce8750, 0x2, 0x2, 0x1036da60, 0x10ce8750)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:766 +0x20e fp=0x10d95f00 sp=0x10d95e8c pc=0x847b03e
github.com/spf13/cobra.(*Command).ExecuteC(0x1036e960, 0x1, 0x804c5b6, 0x10cd0030)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:850 +0x284 fp=0x10d95fa0 sp=0x10d95f00 pc=0x847b944
github.com/spf13/cobra.(*Command).Execute(0x1036e960, 0x1, 0x0)
	/home/prvst/go/src/github.com/spf13/cobra/command.go:800 +0x21 fp=0x10d95fb4 sp=0x10d95fa0 pc=0x847b6a1
github.com/prvst/philosopher/cmd.Execute()
	/home/prvst/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x23 fp=0x10d95fcc sp=0x10d95fb4 pc=0x852bc73
main.main()
	/home/prvst/go/src/github.com/prvst/philosopher/main.go:19 +0x5b fp=0x10d95fd0 sp=0x10d95fcc pc=0x853233b
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x206 fp=0x10d95ff0 sp=0x10d95fd0 pc=0x80701a6
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1324 +0x1 fp=0x10d95ff4 sp=0x10d95ff0 pc=0x8096711
```

**Comment by prvst** [comment]
@FantacticMisterFox 
The program can handle larger databases without any issue, if you send me your file I can take a look.

**Comment by FantacticMisterFox** [comment]
http://www.bioinf.uni-leipzig.de/~john/6frame_SIHUMI.tar.gz
At the time of crashing I still have 40GB of RAM left. So if database is not allocating that amount of memory at once my machine should be fine.
thanks

**Comment by prvst** [comment]
@FantacticMisterFox 

Could you share the file with me again ? the link is not working.

**Comment by FantacticMisterFox** [comment]
sorry was overly eager cleaning. I run it again and make the link available again asap.

**Comment by FantacticMisterFox** [comment]
should be available again

**Comment by prvst** [comment]
Also which command did you executed ?

**Comment by FantacticMisterFox** [comment]
I ran it on my workstation fedora 28 16GB (4GB still available when job crashed) and on our server fedora 24 (eof) 1000GB more than 500GB available when started the last job. Both crash with the following database command with the same error as above. 

```
philosopher_linux_386 workspace --init
philosopher_linux_386 database --custom fake_uni_current_db.fasta
```

I used a knew database with the fake uniprot headers:
http://www.bioinf.uni-leipzig.de/~john/fake_uni_current_db.fasta.tar.gz
Still crashes.

**Comment by prvst** [comment]
I noticed that you are using the X86 version of Philosopher. What OS architecture are you using ? 32bits or 64 bits ? If you are not sure, open a terminal, type the following and paste the result here:

`arch`

**Comment by FantacticMisterFox** [comment]
x86_64

**Comment by prvst** [comment]
You are using the i386 version that limits the memory usage to 4 GB. I recently removed the i386 version, I suggest that you download a fresh copy and try again.
